# Generated by Django 5.2.4 on 2025-07-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('hiphop', 'Hip Hop/Rap'), ('rnb', 'R&B'), ('edm', 'Electronic/Dance'), ('rock', 'Rock'), ('alternative', 'Alternative'), ('country', 'Country'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('other', 'Other')], max_length=50)),
                ('link_type', models.CharField(choices=[('spotify', 'Spotify'), ('youtube', 'YouTube Music')], max_length=20)),
                ('music_link', models.URLField()),
                ('song_file', models.FileField(blank=True, null=True, upload_to='song_submissions/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('social_media', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song Submission',
                'verbose_name_plural': 'Song Submissions',
            },
        ),
    ]
