# Generated by Django 5.2.4 on 2025-07-25 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['price'],
            },
        ),
        migrations.AlterModelOptions(
            name='songsubmission',
            options={'ordering': ['-submission_date'], 'verbose_name': 'Song Submission', 'verbose_name_plural': 'Song Submissions'},
        ),
        migrations.AddField(
            model_name='songsubmission',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='songsubmission',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='songsubmission',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Flutterwave transaction reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='songsubmission',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself and your music'),
        ),
        migrations.AlterField(
            model_name='songsubmission',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this submission'),
        ),
        migrations.AlterField(
            model_name='songsubmission',
            name='social_media',
            field=models.CharField(blank=True, help_text='Your Instagram/Twitter handle', max_length=100),
        ),
        migrations.AlterField(
            model_name='songsubmission',
            name='song_file',
            field=models.FileField(blank=True, help_text="Upload your song file if you don't have a streaming link", null=True, upload_to='song_submissions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='songsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songsubmission',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Selected package for this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.package'),
        ),
        migrations.AddIndex(
            model_name='songsubmission',
            index=models.Index(fields=['artist_name'], name='landing_son_artist__8e1b85_idx'),
        ),
        migrations.AddIndex(
            model_name='songsubmission',
            index=models.Index(fields=['song_title'], name='landing_son_song_ti_854f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='songsubmission',
            index=models.Index(fields=['submission_date'], name='landing_son_submiss_3ad478_idx'),
        ),
        migrations.AddIndex(
            model_name='songsubmission',
            index=models.Index(fields=['payment_status'], name='landing_son_payment_11c9f0_idx'),
        ),
    ]
