# Generated by Django 5.2.4 on 2025-07-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_package_alter_songsubmission_options_and_more'),
        ('payment', '0002_alter_package_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsubmission',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Selected package for this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.package'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
