# Generated by Django 5.2.4 on 2025-07-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['price'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
